urls.py
from django.urls import path, include

from . import views

app_name = 'jiboia'

urlpatterns = [
    path('', views.index, name='index'),
    path('projetos/', views.projetos, name='projetos'),
    path('projetos/<int:projeto_id>/', views.projetos, name='projetos'),

    path('projetos/<int:projeto_id>/atividades/', views.atividades, name='atividades'),
    path('projetos/<int:projeto_id>/atividades/<int:atividade_id>/', views.atividades, name='atividades'),
    
    path('projetos/<int:projeto_id>/atividades/<int:atividade_id>/acoes/', views.acoes, name='acoes'),
    path('projetos/<int:projeto_id>/atividades/<int:atividade_id>/acoes/<int:acao_id>/', views.acoes, name='acoes'),

    path('projetos/<int:projeto_id>/atividades/<int:atividade_id>/notas/', views.notas, name='notas'),
    path('projetos/<int:projeto_id>/atividades/<int:atividade_id>/notas/<int:nota_id>/', views.notas, name='notas'),
]

models.py
#-*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.utils.html import format_html

# Create your models here.

CHOICE_WORKSPACE_ATIVIDADE = (
    ('a-fazer', 'A Fazer'),
    ('desenvolvimento', 'Desenvolvimento'),
    ('concluido', 'Concluido'),
    ('cancelado', 'Cancelado')
)


class Projeto(models.Model):
    """
    Essa classe armazena as informeções gerais dos projetos,
    possui um relacinamento com ativdade e membro isso significa que
    uma ou mais instancias dessa classe complementa suas informações.
    """
    nome = models.CharField(max_length=200)
    descricao = models.TextField(null=True, blank=True)
    criacao_at = models.DateTimeField(auto_created=True)
    inicio_at = models.DateField(null=True, blank=True)
    termino_at = models.DateField(null=True, blank=True)
    executado = models.PositiveIntegerField()
    status = models.BooleanField(default=False)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.nome


    @property
    def content_type(self):
        return 'at_projeto'


    @property
    def is_status(self):
        if status:
            return 'Bloqueado'
        return 'Em produção'


class Atividade(models.Model):
    """
    Essa classe abstrai uma disciplina do pecesso de desenvolvimento em um projeto.
    possui um relacionamento de agregação com as class ações e que
    podem produzir uma serie de artefatos que contempla suas informções.
    """
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE, related_name='atividades_deste')
    prioridade = models.PositiveIntegerField(default=1)
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    inicio_at = models.DateField(null=True, blank=True)
    termino_at = models.DateField(null=True, blank=True)
    criacao_at = models.DateTimeField(auto_created=True)
    workflow = models.CharField(max_length=30, choices=CHOICE_WORKSPACE_ATIVIDADE, default='a-fazer')
    notas = models.ManyToManyField('BlocoNota', blank=True)
    artefatos = models.ManyToManyField('Artefato', blank=True)


    @property
    def tolltip(self):
        html_tag = '%s\n%s' % (self.nome, self.descricao)
        return format_html(html_tag)
    

    @property
    def producao(self):
        concuidos = self.acoes_desta.filter(status=True).count()
        aguardando = self.acoes_desta.filter(status=False).count()
        if not aguardando:
            return '100.0'
        
        total = concuidos + aguardando
        total = (concuidos*100)/total
        return ('%s') % round(total,0)


class Acao(models.Model):
    """
    Essa class abstai uma tarrefa representa as ações tomadas por um atividade,
    """
    atividade = models.ForeignKey('Atividade',  on_delete=models.CASCADE, related_name='acoes_desta')
    nome = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)
    criacao_at = models.DateTimeField(auto_created=True)
    inicio_at = models.DateField(null=True, blank=True)
    termino_at = models.DateField(null=True, blank=True)
    prioridade = models.PositiveIntegerField(default=1)
    status = models.BooleanField(default=False)


    @property
    def tolltip(self):
        html_tag = '%s\n%s' % (self.nome, self.descricao)
        return format_html(html_tag)
    

    @property
    def is_status(self):
        if self.status:
            return '[Finalizado]'
        return '[Aguardando]'
    

    def get_absolute_url(self):
        return '/jiboia/projetos/%s/atividades/%s/acoes/%s/' % (self.atividade.projeto.id, self.atividade.id, self.id)


class Artefato(models.Model):
    """
    Essa classe representa um documento produzido durante as fazes do projeto
    em suas atividades em função de alguma ação especifica.
    """
    nome = models.CharField(max_length=200)
    criacao_at = models.DateTimeField(auto_created=True)
    arquivo = models.FileField(upload_to='jiboia-doc/artefatos/')

    @property
    def tolltip(self):
        html_tag = '%s' % (self.nome)
        return format_html(html_tag)


class BlocoNota(models.Model):
    """
    Essa classe representa as anotações produzidas nas fase do projeto providadas
    de uma atividade ou ação.
    """
    nota = models.TextField()
    criacao_at = models.DateTimeField(auto_created=True)
    status = models.BooleanField(default=False)

    @property
    def is_status(self):
        if self.status:
            return 'Processada'
        else:
            return 'Aguardando'

#Classes de modelo de controle

class Papel(models.Model):
    """
    Essa class representa uma permissão especifica,
    exercido por um membro ou grupo.
    """
    nome = models.CharField(max_length=30)


class Grupo(models.Model):
    """
    Essa class representa um grupo contendo uma ou muitos papeis,
    representada pelo relacinamento com papeis. 
    """
    nome = models.CharField(max_length=20)
    papeis = models.ManyToManyField('Papel', blank=True)


class Membro(models.Model):
    """
    Essa class representa um membro de um projeto,
    esta relacionado com um ou mais grupos
    ou pode possuir um papel especifico para um determinado
    projeto.
    """
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE, related_name='membros_deste')
    grupos = models.ManyToManyField('Grupo', blank=True)
    papeis = models.ManyToManyField('Papel', blank=True)
    criacao_at = models.DateTimeField(auto_created=True)

templates/jiboia/componentes/aux_ajax_form.html
{% if opcao == 'forms' %}
{% load bootstrap %}
{% csrf_token %}
{{ form|bootstrap }}
{% endif %}

{% if opcao == 'workflow' %}
{% csrf_token %}
<p style="font-weight: bold">Fluxo de trabalho.</p>
<ul>
    <li><input type="radio" value="a-fazer" name="workflow" />&nbsp;A Fazer. </li>
    {% if object.workflow != 'desenvolvimento' %}
    <li><input type="radio" value="desenvolvimento" name="workflow" />&nbsp;Desenvolvimento. </li>
    {% endif %}
    {% if object.workflow != 'concluido' %}
    <li><input type="radio" value="concluido" name="workflow" />&nbsp;Concluido. </li>
    {% endif %}
    {% if object.workflow != 'cancelado' %}
    <li><input type="radio" value="cancelado" name="workflow" />&nbsp;Cancelado. </li>
    {% endif %}

</ul>
{% endif %}

{% if opcao == 'view-atividade' %}
<p style="font-weight: bold">{{object.descricao}}</p>
<p><strong>Início:</strong>&nbsp;{{object.inicio_at|date:'d/m/Y'}}</p>
<p><strong>Encerramento:</strong>&nbsp;{{object.termino_at|date:'d/m/Y'}}</p>
<p><strong>Andamento da atividade:</strong>&nbsp;{{object.producao}}%</p>
<p><strong>Fluxo de trabalho:</strong>&nbsp;{{object.get_workflow_display}}</p>
<hr>

<p><strong>Tarefas:</strong></p>
<ul>
    {% if acoes %}
        {% for acao in acoes %}
            <li><span class="badge badge-warning">{{acao.is_status}}</span><br>{{acao.nome}}</li>
        {% endfor %}
    {% else %}
        <li>Nenhuma ação definida.</li>
    {% endif %}
</ul>

<p><strong>Notas:</strong></p>
{% with notas=object.notas.all %}
<ul>
    {% if notas %}
        {% for nota in notas %}
            <li><span class="badge badge-warning">[{{nota.is_status}}]</span><br>{{nota.nota}}</li>
        {% endfor %}
    {% else %}
        <li>Nenhuma nota definida.</li>
    {% endif %}
</ul>
{% endwith %}
</div>
{% endif %}


{% if opcao == 'acoes-atividade' %}
<ul id="lista-acoes">
    {% for item in objects %}
    <li><span class="badge badge-warning">{{ item.is_status }}</span><br>
        <a href="#" onclick="run(
        '{{item.get_absolute_url}}', {'action':'@@update'}
        ); enable_button_and_save(
        '{{item.get_absolute_url}}?action=@@update'
        )">
        <strong>{{item.nome}}</strong>
        </a><br><i>{{item.descricao}}</i>
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/jiboia/componentes/aux_taglibs.html
{% if objects %}
{% if opcao == 'atividades' %}
<ul style="list-style: none; padding: 0;" id="ordenador">
        {% for item in objects %}
        <li class="alert bg-white" style="border: 1px #ddd solid;">
                <a href="#" data-toggle="collapse" title="{{ item.tolltip }}" aria-expanded="false" aria-controls="#collapse_{{ item.id }}"
                        data-target="#collapse_{{ item.id }}">{{item.nome|truncatechars:27}}
                </a>

                <div class="progress">
                        {% if item.workflow == 'concluido' %}
                        <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100"
                                aria-valuemin="0" aria-valuemax="100">100%</div>
                        {% elif item.workflow != 'a-fazer' %}
                        <div class="progress-bar" role="progressbar" style="width: {{item.producao}}%;" aria-valuenow="100"
                                aria-valuemin="0" aria-valuemax="100">{{item.producao}}%</div>
                        {% endif %}
                </div>

                <!--<div class="dropdown" style="margin-top: 5px;">
                        <button class="btn btn-outline-secondary btn-sm btn-block dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Workflow
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Iniciar atividade</a>
                                <a class="dropdown-item" href="#">Fazendo</a>
                                <a class="dropdown-item" href="#">Concluido</a>
                                <a class="dropdown-item" href="#">Cancelada</a>
                        </div>
                </div>-->

                <div class="collapse" id="collapse_{{ item.id }}" style="margin-bottom: 1em;">
                        <div class="card-body" style="border: 1px #ddd solid;">
                                <p style="font-weight: bolder">{{ item.nome }}</p>
                                <p>{{item.descricao|truncatewords:10}}</p>

                                {% if item.workflow == 'a-fazer' %}
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:atividades' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='atividades' data-action="@@workflow" data-toggle="modal">
                                        <span class="badge badge-primary">Iniciar</span></a>&nbsp;
                                {% else %}
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:atividades' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='atividades' data-action="@@workflow" data-toggle="modal">
                                        <span class="badge badge-primary">Workflow</span></a>&nbsp;
                                {% endif %}
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:atividades' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='atividades' data-action="@@update" data-toggle="modal">
                                        <span class="badge badge-primary">Editar</span></a>&nbsp;
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:atividades' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='atividades' data-action="@@open-object" data-toggle="modal">
                                        <span class="badge badge-primary">Abrir</span></a>
                                <hr>
                                <span style="font-size: 75%; font-weight: bold;">Tarefas&nbsp;-&nbsp;<span class="badge badge-secondary">{{item.acoes_desta.count}}</span></span><br>
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:acoes' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='acoes' data-action="@@create" data-toggle="modal">
                                        <span class="badge badge-danger">Nova tarefa</span></a>&nbsp;
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:acoes' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='acoes' data-action="@@list-all" data-toggle="modal">
                                        <span class="badge badge-danger">Listar</span></a>
                                <hr>
                                <span style="font-size: 75%; font-weight: bold;">Notas&nbsp;-&nbsp;<span class="badge badge-secondary">{{item.notas.count}}</span></span><br>
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:notas' item.projeto.id item.id %}"
                                        data-modulo='notas' data-action="@@create" data-toggle="modal">
                                        <span class="badge badge-warning">Nova nota</span></a>&nbsp;
                                <a href="#" data-target="#form-modal" data-titulo="{{ item.nome|truncatewords:7 }}"
                                        data-url="{% url 'jiboia:notas' projeto_id=item.projeto.id atividade_id=item.id %}"
                                        data-modulo='notas' data-action="@@list-all" data-toggle="modal">
                                        <span class="badge badge-warning">Listar</span></a>
                                
                                
                        </div>
                </div>
        </li>
        {% endfor %}
</ul>
{% endif %}
{% endif %}